### ISSUE TITLE
gr8 workfow! but why not sharing the code ?

### ISSUE THREAD

**Issue by viggin543** [BenziAhamed/Streaks#1]
a  Mach-O 64-bit executable x86_64 file is very nice, but not humanly readable  :) 
did you write it in `go` ?

**Comment by BenziAhamed** [comment]
The code was written in Swift.

Don't mind sharing code at all, but I don't have access to it due to the laptop dying out on me.

The SSD is perhaps salvageable, but don't have the resources to do that right now.
